version: '3.5'

services:
  dsh-annotator:
    build: ./
    #image: dsh_annotator:latest
    restart: always
    environment:
      - portNumber= 8080

        # The URL path at which the container listens for API requests
        # OPTIONAL - default "/process"
      - urlPath= "/process"

        # Can this endpoint accept cleartext HTTP/2 requests (true) or should we use HTTP/1.1 (false)
        # OPTIONAL - default false
      - supportsHttp2= false

        # Annotation set name into which un-mapped annotation types should be placed
        # OPTIONAL - see "annotation mappings" documentation for details
      - outputASName= "Self-harm"


        # Ideal number of parallel requests that a single instance of this container can
        # handle.  The actual concurrency may be greater than this if there is insufficient
        # memory to run enough replicas.
        # OPTIONAL - if omitted we assume a single replica will always be enough to handle
        # as many parallel requests as there are GCP threads on the processing node
      - targetConcurrency= 3

        # Environment variables to pass to the container process.  In addition to fixed
        # values, you can use ${APP_CONCURRENCY} to pass in a number giving the actual
        # expected concurrency level for this container (which may be more than
        # targetConcurrency if memory is low, but capped at the number of GCP threads).
        # The container may wish to use this value to size its internal data structures
        # such as thread pools.
        # OPTIONAL

      - CONCURRENCY= "${APP_CONCURRENCY}"

        # A more flexible way to map the annotation types returned by the container
        # endpoint into annotation sets and types in GATE, overriding the default
        # behaviour of using the ELG annotation type as-is for the type, and putting
        # the annotations in the set specified by outputASName.  Keys in this mapping
        # are the annotation types as returned by the endpoint, and the values are
        # GATE-style annotation selector expressions setName:annType exactly as used
        # in the metadata and db-mappings.
        # OPTIONAL
        # annotationTypeMapping:
        #  "/activity/prescription": "Drug:Prescription"
    #expose:
    #- 8080
    ports:
    - 8080:8000